# Generated by Django 5.0.2 on 2024-02-15 05:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.UUIDField(auto_created=True, default=uuid.uuid4)),
                ('empname', models.TextField(max_length=500)),
                ('empemail', models.TextField(max_length=500)),
                ('empgender', models.TextField(max_length=10)),
                ('empcreation', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
