# Generated by Django 5.0.2 on 2024-02-15 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_tasks_emprole'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tasks',
            new_name='employee',
        ),
    ]
