# Generated by Django 5.0.2 on 2024-02-15 04:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskID', models.UUIDField(auto_created=True, default=uuid.uuid4)),
                ('employeeID', models.IntegerField()),
                ('todotask', models.TextField(max_length=5000)),
                ('status', models.BinaryField()),
                ('taskcreation', models.DateTimeField(auto_now=True)),
                ('taskcompletion', models.DateField()),
            ],
        ),
    ]
