# Generated by Django 5.0.2 on 2024-02-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='employeeID',
            field=models.TextField(),
        ),
    ]
