# Generated by Django 5.0.2 on 2024-02-15 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasks_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='employeeID',
            new_name='empname',
        ),
    ]
